### ISSUE TITLE
resolveDirectory fails for packages that specify an object in package.json browser field

### ISSUE THREAD

**Issue by BigDataSamuli** [ivogabe/small#9]
Hi,

Apparently some npm packages (e.g. [asap](https://www.npmjs.com/package/asap)) specify an object in package.json's browser field (see [https://github.com/defunctzombie/package-browser-field-spec](https://github.com/defunctzombie/package-browser-field-spec)). This causes small to fail in the Resolve.resolveDirectory function as path.join throws
```
TypeError: Path must be a string. Received { './asap': './browser-asap.js',
  './asap.js': './browser-asap.js',
  './raw': './browser-raw.js',
  './raw.js': './browser-raw.js',
  './test/domain.js': './test/browser-domain.js' }
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    ...
```
Maybe emit a warning and fall back to the main field in these cases, and/or allow selecting the preferred main file (e.g. main or browser)? Or implement the extended browser field spec.

**Comment by ivogabe** [comment]
Thanks for reporting, I wasn't aware of that. Small should support objects in the `browser` field. I have some other business to do the following days. Could you try to create a PR? Otherwise I'll take a look at it next week.

**Comment by BigDataSamuli** [comment]
No sorry I don't really need the enhanced browser field functionality and I was actually mostly just testing Small around due to other more well-know module bundlers not really playing well with gulp.

**Comment by ivogabe** [comment]
Ok, I'll then take a look at it soon.
